name: DataOps Pipeline

on:
  push:
    branches:
      - main  # ou la branche sur laquelle tu veux que le workflow se déclenche
  pull_request:
    branches:
      - main  # ou la branche de destination du pull request

jobs:
  run_dataops_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Vérification du code
        uses: actions/checkout@v2  # Télécharge le code du repo

      - name: Configurer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # spécifie la version de Python que tu veux

      - name: Installer les dépendances
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Exécuter le pipeline DataOps
        run: |
          source venv/bin/activate
          python main.py  # Exécute ton script principal

